# Generated by Django 5.2.1 on 2025-05-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadOrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=255)),
                ('paas_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pag_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_psc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.approvalstatus')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.country')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.fund')),
                ('lead_org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.leadorgunit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.donor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'donor')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='donors',
            field=models.ManyToManyField(through='projects.ProjectDonor', to='projects.donor'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.theme'),
        ),
    ]
